apiVersion: v1
kind: Service
metadata:  
  name: unstructured  
spec:  
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: unstructured
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unstructured
  labels:
    app: unstructured
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unstructured
  template:
    metadata:
      labels:
        app: unstructured
    spec:
      containers:
      - name: unstructured
        imagePullPolicy: Always
        image: robwilkes/unstructured-api:latest
        ports:
        - containerPort: 8000  